import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "./_components/Header";
import MiddleHeader from "./_components/MiddleHeader";
import { createClient } from "./_lib/supabase/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  const supabase = await createClient();
  const {data:{user}} = await supabase.auth.getUser();
  return (
    <html lang="ja">
      <body
className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <MiddleHeader />
        <div className="container mx-auto px-4 py-8">
          {children}
        </div>
      </body>
    </html>
  );
}
